import {
  Atom,
  Boot,
  Compass,
  Coins,
  Crown,
  Diamond,
  Eye,
  Flame,
  Flask,
  Hand,
  Heart,
  Knife,
  Lightning,
  Scroll,
  Seal,
  Shield,
  Skull,
  Sphere,
  Sword,
  Trophy,
  Wind,
} from "@phosphor-icons/react"
import type { Icon as PhosphorIcon } from "@phosphor-icons/react"
import type { IconKey } from "@/data/types"

export const ICON_MAP: Record<IconKey, PhosphorIcon> = {
  sword: Sword,
  dagger: Knife,
  spear: Sword,
  shield: Shield,
  helmet: Skull,
  gloves: Hand,
  boots: Boot,
  ring: Seal,
  amulet: Sphere,
  flask: Flask,
  scroll: Scroll,
  gem: Diamond,
  core: Atom,
  lightning: Lightning,
  wind: Wind,
  heart: Heart,
  eye: Eye,
  flame: Flame,
  trophy: Trophy,
  crown: Crown,
  skull: Skull,
  compass: Compass,
  coin: Coins,
}
