import type { SupportedExerciseId } from "./poseTypes"

/**
 * Every tunable number for the pose-detection pipeline lives in this file
 * (claude.md §23 — no magic numbers scattered across detectors). Angles are in
 * degrees, distances are normalized (0–1) image-space fractions, durations in ms.
 */

// MediaPipe Pose's 33 landmark indices — https://ai.google.dev/edge/mediapipe/solutions/vision/pose_landmarker
export const POSE_LANDMARK = {
  nose: 0,
  leftShoulder: 11,
  rightShoulder: 12,
  leftElbow: 13,
  rightElbow: 14,
  leftWrist: 15,
  rightWrist: 16,
  leftHip: 23,
  rightHip: 24,
  leftKnee: 25,
  rightKnee: 26,
  leftAnkle: 27,
  rightAnkle: 28,
} as const

export const POSE_ASSETS = {
  // Self-hosted copies (generated by scripts/setup-pose-assets.mjs, served from this
  // origin so the app works fully offline after `npm install` — see claude.md §18/§21).
  wasmBaseUrl: "/vendor/mediapipe/wasm",
  modelAssetPath: "/vendor/mediapipe/models/pose_landmarker_lite.task",
  // Used only if the local copies above are missing (e.g. setup script couldn't
  // reach the network at install time).
  fallbackWasmBaseUrl: "https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@1.0.1/wasm",
  fallbackModelAssetPath:
    "https://storage.googleapis.com/mediapipe-models/pose_landmarker/pose_landmarker_lite/float16/latest/pose_landmarker_lite.task",
}

export const POSE_DETECTION_CONFIG = {
  numPoses: 1,
  minPoseDetectionConfidence: 0.5,
  minPosePresenceConfidence: 0.5,
  minTrackingConfidence: 0.5,
  /** Per-landmark visibility score (0–1) below which that point isn't trusted. */
  minLandmarkVisibility: 0.5,
  /** Fraction of a detector's required landmarks that must clear `minLandmarkVisibility` to count as "PRONTA". */
  readyVisibleFraction: 0.8,
  /** Below this fraction of required landmarks visible, treat as no pose at all rather than "reposition". */
  noPoseVisibleFraction: 0.35,
}

export const POSE_SMOOTHING_CONFIG = {
  /** Frames averaged for joint-angle smoothing — absorbs camera jitter (claude.md §12). */
  angleSmoothingWindow: 5,
  /** Consecutive frames a new phase candidate must hold before it's confirmed (hysteresis). */
  minFramesPerPhase: 4,
  /** ...and the minimum time that candidate must span, so a fast frame burst can't fake it. */
  minPhaseDurationMs: 150,
  /** Minimum time between two counted reps — blocks double-counting on a single cycle. */
  minRepIntervalMs: 500,
}

export const CALIBRATION_CONFIG = {
  /** Ceremonial countdown shown to the player ("CALIBRANDO POSE... 3 2 1 GO"). */
  durationSeconds: 3,
  /** Real gate: consecutive good-quality frames required before a session is allowed to start counting. */
  requiredStableFrames: 15,
}

export const PUSHUP_CONFIG = {
  /** Elbow angle (shoulder–elbow–wrist) at/under which the rep counts as DOWN. */
  elbowAngleDownMax: 95,
  /** Elbow angle at/over which the rep counts as UP. */
  elbowAngleUpMin: 155,
  /** Shoulder–hip–ankle angle must stay above this to count as a straight (non-sagging) body line. */
  bodyAlignmentMinAngle: 145,
  /**
   * Shoulder–hip line must be within this many degrees of horizontal to be accepted as a
   * push-up posture at all. Without this gate, someone sitting upright at a desk and just
   * bending an elbow (typing, adjusting the camera) can cross the elbow-angle thresholds
   * and rack up "reps" without ever getting on the floor — this blocks that entirely,
   * independent of the elbow angle, since it only needs shoulder+hip (reliable even when
   * the feet aren't in frame, unlike the ankle-based alignment check above).
   * 45 was too strict for a real phone propped on the floor at an angle (not a clean side
   * profile): 2D perspective foreshortening measures the shoulder–hip line as noticeably
   * steeper at the top of the rep (torso higher/closer to the camera) than at the bottom,
   * so legitimate top-of-rep frames were getting rejected as "not lying down". 65 still
   * excludes someone actually standing/sitting (torso angle near 90) with room to spare.
   */
  maxTorsoAngleFromHorizontal: 65,
}

export const SQUAT_CONFIG = {
  /** Knee angle (hip–knee–ankle) at/under which the rep counts as BOTTOM. */
  kneeAngleBottomMax: 100,
  /** Knee angle at/over which the rep counts as STANDING. */
  kneeAngleStandMin: 160,
}

export const RUNNING_CONFIG = {
  /** Minimum normalized knee-lift (relative to hip height) to register as a step. */
  kneeLiftMinDelta: 0.04,
  /** Minimum time between two steps — filters out tremor/noise. */
  minStepIntervalMs: 220,
  /** If no step lands within this window, running is considered stopped. */
  maxStepGapMs: 1500,
}

export const POSE_EXERCISE_LABELS: Record<SupportedExerciseId, string> = {
  flexao: "Flexões",
  agachamento: "Agachamentos",
  corrida: "Corrida",
}

/** Human-readable label for a detector's raw phase string (e.g. "DESCENDO", "CORRENDO"). */
export const POSE_PHASE_LABELS: Record<string, string> = {
  UP: "EM PÉ",
  DOWN: "EMBAIXO",
  DESCENDO: "DESCENDO",
  SUBINDO: "SUBINDO",
  STANDING: "EM PÉ",
  BOTTOM: "EMBAIXO",
  DESCENDING: "DESCENDO",
  ASCENDING: "SUBINDO",
  CORRENDO: "CORRENDO",
  PARADO: "PARADO",
}

export const CAMERA_CONSTRAINTS: MediaTrackConstraints = {
  width: { ideal: 1280 },
  height: { ideal: 720 },
  frameRate: { ideal: 30, max: 30 },
}
